name: Build and Release Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debootstrap xorriso genisoimage binutils squashfs-tools \
          grub-pc-bin grub-efi-amd64-bin dosfstools mtools xz-utils zstd \
          curl rsync dpkg-dev debhelper devscripts build-essential fakeroot \
          lintian dh-make pandoc

    - name: Build deb package
      run: |
        echo "Building deb package..."
        chmod +x tools/build-package.sh
        sudo ./tools/build-package.sh
        echo "deb package build completed."

    - name: Archive deb package
      uses: actions/upload-artifact@v3
      with:
        name: minios-live-${{ env.DATE }}
        path: build/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Create Pre-release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ github.run_id }}
        release_name: Nightly Build ${{ github.run_id }}
        draft: false
        prerelease: true

    - name: Upload Release Assets
      run: |
        for artifact in ./artifacts/*; do
          asset_name=$(basename $artifact)
          echo "Uploading $asset_name"
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$artifact" \
            "${{ steps.create_release.outputs.upload_url }}?name=$asset_name"
        done
